### ISSUE TITLE
Add persistence to the signing round in WSTS

### ISSUE THREAD

**Issue by jferrant** [xoloki/wsts#35]
Stacks signer needs to be able to read stacker-db state and feed the messages into its coordinator and signing round to return to its state prior to the crash. The coordinator component seems to operate correctly, however the signer state cannot be deterministically replicated without the private polys being loaded from persistent state

**Comment by rondales** [comment]
> Stacks signer needs to be able to read stacker-db state and feed the messages into its coordinator and signing round to return to its state prior to the crash. The coordinator component seems to operate correctly, however the signer state cannot be deterministically replicated without the private polys being loaded from persistent state

**Comment by xoloki** [comment]
Fixed in #57
