### ISSUE TITLE
Clean up error handling in `compute_secrets`

### ISSUE THREAD

**Issue by xoloki** [xoloki/wsts#47]
`v1::Party::compute_secrets` checks for missing private shares `from` a particular `key_id`, while `v2` checks for shares missing `for` a particular `key_id`.  Both are actually useful pieces of information, so we should change `DkgError::MissingPrivateShares` to capture both.

We also need to be able to resolve discrepancies if we have non-overlapping sets of `DkgPublicShares` and `DkgPrivateShares`.  The `fire::Coordinator` should make sure that this does not happen, but in case it slips through consider the set of public shares to be canonical.

**Comment by jferrant** [comment]
I think this was fixed already by https://github.com/Trust-Machines/wsts/commit/47290393c9760b0d60b3ced231d6fe30173d27b1

**Comment by xoloki** [comment]
> I think this was fixed already by [4729039](https://github.com/Trust-Machines/wsts/commit/47290393c9760b0d60b3ced231d6fe30173d27b1)

We made progress on this in that commit, but PR #95 will do more!
