### ISSUE TITLE
Add save/load functionality to all non config data within the signer and coordinator state machines

### ISSUE THREAD

**Issue by jferrant** [xoloki/wsts#54]
Applications built on top of wsts may crash and wish to be able to persist their dkg rounds/signing rounds between crashes. 

There is already some save/load functionality for wsts::v2::Signer. Expand this to include all non config data within the signer and coordinator state machines.

**Comment by netrome** [comment]
PR in Stacks fork https://github.com/stacks-network/wsts/pull/1

**Comment by xoloki** [comment]
Fixed in #57
