### ISSUE TITLE
Use generics instead of hard-coding OsRng

### ISSUE THREAD

**Issue by netrome** [xoloki/wsts#63]
Spawned from https://github.com/stacks-network/stacks-core/pull/4659#discussion_r1560665096

Wsts currently hard-codes OsRng in multiple places. It should be up to the user of the library to choose the specific rng to use.

### Definition of done
The `wsts` library does not hard code the random number generator in any logic callable by downstream users.

**Comment by tonyjzhou** [comment]
@xoloki Can you please assign me the issue to me?

**Comment by xoloki** [comment]
> @xoloki Can you please assign me the issue to me?

Done!

**Comment by tonyjzhou** [comment]
Done
