### ISSUE TITLE
Clean up logging with named parameters

### ISSUE THREAD

**Issue by xoloki** [xoloki/wsts#99]
The `tracing` crate has support for logging named parameters, which `wsts` does not currently use.  This makes the logs more explicit, and tracks how other crates use them.

So instead of
```
info!("Signer {} received DkgPublicShares", signer_id);
```
We could instead do
```
info!(%signer_d, "received DkgPublicShares");
```

**Comment by tonyjzhou** [comment]
@xoloki PR for review: https://github.com/Trust-Machines/wsts/pull/102

**Comment by tonyjzhou** [comment]
Done
